version: '3'

services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./config/postgres.conf:/etc/postgresql/postgresql.conf
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    expose:
      - "5432"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"

  redis:
    image: redis:6.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data
    ports:
      - "16379:6379"
    expose:
      - "6379"

  contractor-web:
    build:
      context: ./contractor
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    depends_on:
      - db
      - rabbitmq
      - redis
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_API_HOST: rabbitmq
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./contractor:/app

  contractor-sidekiq:
    build:
      context: ./contractor
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq
    depends_on:
      - db
      - rabbitmq
      - redis
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_API_HOST: rabbitmq
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./contractor:/app

  contractor-consumer:
    build:
      context: ./contractor
      dockerfile: Dockerfile.dev
    command: dockerize -wait tcp://rabbitmq:5672 -timeout 30s bundle exec hutch
    depends_on:
      - db
      - rabbitmq
      - redis
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_API_HOST: rabbitmq
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./contractor:/app

  manager-web:
    build:
      context: ./manager
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    depends_on:
      - db
      - rabbitmq
      - redis
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_API_HOST: rabbitmq
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./manager:/app

  manager-consumer:
    build:
      context: ./manager
      dockerfile: Dockerfile.dev
    command: dockerize -wait tcp://rabbitmq:5672 -timeout 30s bundle exec hutch
    depends_on:
      - db
      - rabbitmq
      - redis
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_API_HOST: rabbitmq
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./manager:/app
